## **Introduction to Colab and Python**

**Welcome to Colab!**

We will give you a short introduction to the Python programming language and the environment used for the course's activities: *Colab*.

Colab is a Python development environment that runs in the browser using Google Cloud.

In Colab there exists two kinds of cells: This one here is a text (markdown) cell. There other type is a code cell which you see below.

For example, to print "Hello World", just hover the mouse over [ ] on the left side of the code cell below and press the play button to the upper left. Or click into the cell and press the shift key and the enter key simultaneously to execute.

In [1]:
print("Hello World")

Hello World


You just code normal python code in the code cells and execute it. The result of the last code line will be displayed

In [2]:
1+1

2

## Functions, Conditionals, and Iteration
Let's create a Python function, and call it from a loop.

In [8]:
def x_cubed(x):
  return x * x * x

for i in range(1, 10, 2):  # i=1, 3, 5, 7, 9 (start, stop, step) stop value is not included
  print("- {}. round - now running with i: {}".format(i//2+1,i))
  r = x_cubed(i)
  print("Result from x^3: {}\n".format(r))

- 1. round - now running with i: 1
Result from x^3: 1

- 2. round - now running with i: 3
Result from x^3: 27

- 3. round - now running with i: 5
Result from x^3: 125

- 4. round - now running with i: 7
Result from x^3: 343

- 5. round - now running with i: 9
Result from x^3: 729



Easy, right?

If you want a loop starting at 0 to 2 (exclusive) you could do any of the following

In [10]:
print("Iterate over the items. 'range(2)' is like a list [0,1].")
for i in range(2):
  print(i)

print("Iterate over an actual list.")
for i in [0,1]:
  print(i)

print("While works")
i = 0
while i < 2:
  print(i)
  i += 1

Iterate over the items. 'range(2)' is like a list [0,1].
0
1
Iterate over an actual list.
0
1
While works
0
1


## Numpy and lists
Python has lists to store values together directly built into the language.
However, we will use a library called numpy for our computations.
Numpy gives us a lot of useful functions for doing Deep Learning and Machine Learning.

Here, you will also see an import statement. This statement makes the entire numpy package available and we can access those symbols using the abbreviated 'np' syntax.

In [20]:
import numpy as np  # Make numpy available using np.

# Create a 1D numpy array, and append an element
a = np.array([1,2,3])
a = np.append(a, 4)
print("1D array:")
print(a)

# Create a 2D numpy array
b= np.array([[1,2],[3,4]])

print("2D array:")
print(b)

1D array:
[1 2 3 4]
2D array:
[[1 2]
 [3 4]]


In [21]:
#indexing numpy arrays arrayname[x,y]
print(b[0,0])
print(b[0,1])

1
2


In [22]:
print("\nShowing some basic math on arrays")
c = np.array([0,1,4,3,2])
print("Max: {}".format(np.max(b)))
print("Average: {}".format(np.average(b)))
print("Max index: {}".format(np.argmax(b)))


Showing some basic math on arrays
Max: 4
Average: 2.5
Max index: 3


In [24]:
print("\nUse numpy to create a [3,3] dimension array with random number")
d = np.random.rand(3, 3)
print(d)


Use numpy to create a [3,3] dimension array with random number
[[0.47341676 0.49379487 0.40657184]
 [0.84450555 0.70311934 0.17756147]
 [0.31973831 0.29098035 0.58399254]]


In [25]:
print("\nYou can print the dimensions of arrays")
print("Shape of d: {}".format(d.shape))



You can print the dimensions of arrays
Shape of d: (3, 3)


## Colab Operations

Colab is a virtual machine you can access directly. To run commands at the VM's terminal, prefix the line with an exclamation mark -> *! commandname* . See examples below ->


In [28]:
print("\nDoing $ls on filesystem")
!ls
!pwd


Doing $ls on filesystem
sample_data
/content


In [29]:
print("Install numpy")  # Just for test, numpy is actually preinstalled in all Colab instances
!pip install numpy

Install numpy


All usage of Colab in this course is completely free! Even GPU usage is provided free of charge for some hours of usage every day.

**Using GPUs**
* Many of the activities in this course executes much more quickly by using GPU runtime: Runtime | Change runtime type | Hardware accelerator | GPU
* Attention: If you change the runtime to GPU all code have to be reexecuted. So have your results in a file if you want to keep them.

**Some final words on Colab**
*   You execute each cell in order, you can edit & re-execute cells if you want
*   Sometimes, this could have unintended consequences. For example, if you add a dimension to an array and execute the cell multiple times, then the cells after may not work. If you encounter problem reset your environment:
  *   Runtime -> Restart runtime... Resets your Python shell
  *   Runtime -> Restart all runtimes... Will reset the Colab image, and get you back to a 100% clean environment
* You can also clear the output in the Colab by doing: Edit -> Clear all outputs
* Colab notebooks in this course are loaded from GitHub. Save to your Google Drive if you want a copy with your code/output: File -> Save a copy in Drive...
